### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain-lang.org#46]
It'd be pretty sick if there were a dark mode option for the docs.

**Comment by spotandjake** [comment]
Docs
./docs/style.css
===============
add
```css
html {
  --Background: #121212;
  --Border: #333;
  --lavender: #444;
  --black: #eee;
}
html {
  background: var(--Background);
}
```
Main Page
./stylesheets/style.css
===============
add
```css
html {
  --Background: #121212;
  --Border: #333;
  --lavender: #444;
  --black: #eee;
}
html {
  background: var(--Background);
}
```
Blog
./blog/css/style.css
===============
add
```css
html {
  --Background: #121212;
  --Border: #333;
  --lavender: #444;
  --black: #eee;
  --gray3: #9e9eb1;
}
html {
  background: var(--Background);
}
.join-mailing {
  background: var(--Background) !important;
}
.button.mc-submit {
  color: var(--orange) !important;
}
```
if you implemented the following colours it would look pretty good you can see it here, and it requires minimal changes after that you could just add a toggle switch up in the top by the Github and Twitter buttons. https://grainorg.spotandjake.repl.co/
